export const defaultSettings = {
  locale: "en",
  use_msal: false,
  fullscreen: false,
  resolution: 720,
  xhome_auto_connect_server_id: '',
  xhome_bitrate_mode: "Auto",
  xhome_bitrate: 20,
  xcloud_bitrate_mode: "Auto",
  xcloud_bitrate: 20,
  audio_bitrate_mode: "Auto",
  audio_bitrate: 20,
  enable_audio_control: false,
  enable_audio_rumble: false,
  audio_rumble_threshold: 0.15,
  preferred_game_language: "en-US",
  force_region_ip: "",
  codec: "",
  polling_rate: 250,
  coop: false,
  vibration: true,
  vibration_mode: "Native",
  gamepad_kernal: "Native",
  gamepad_mix: false,
  gamepad_index: -1,
  dead_zone: 0.1,
  edge_compensation: 0,
  force_trigger_rumble: '',
  power_on: false,
  video_format: "",
  virtual_gamepad_opacity: 0.6,
  gamepad_maping: null,
  native_gamepad_maping: null,
  ipv6: false,
  enable_native_mouse_keyboard: false,
  mouse_sensitive: 0.5,
  performance_style: false,
  server_url: '',
  server_username: '',
  server_credential: '',
  background_keepalive: false,
  input_mousekeyboard_maping: {
    ArrowLeft: 'DPadLeft',
    ArrowUp: 'DPadUp',
    ArrowRight: 'DPadRight',
    ArrowDown: 'DPadDown',

    Enter: 'A',
    k: 'A',

    Backspace: 'B',
    l: 'B',

    j: 'X',
    i: 'Y',

    '2': 'LeftShoulder',
    '3': 'RightShoulder',

    '1': 'LeftTrigger',
    '4': 'RightTrigger',

    '5': 'LeftThumb',
    '6': 'RightThumb',

    'a': 'LeftThumbXAxisPlus',
    'd': 'LeftThumbXAxisMinus',
    'w': 'LeftThumbYAxisPlus',
    's': 'LeftThumbYAxisMinus',

    'f': 'RightThumbXAxisPlus',
    'h': 'RightThumbXAxisMinus',
    't': 'RightThumbYAxisPlus',
    'g': 'RightThumbYAxisMinus',

    v: 'View',
    m: 'Menu',
    n: 'Nexus',
  },
  display_options: {
    sharpness: 5,
    saturation: 100,
    contrast: 100,
    brightness: 100,
  },
  use_vulkan: false,
  fsr: false,
  fsr_sharpness: 2,
  debug: false,
};
